# ENCONTRANDO EL NUMERO MAYOR DE UNA LISA

numeros = [3,5,7,8,9]
numeros_mas_altos = max(numeros)
print(numeros_mas_altos)

# LO MISMO SE PUEDE HACER PARA EL MINIMO

# REDONDEANDO A 6 DECIMALES (EN ESTE CASO LO QUE HACEMOS ES QUE AGREGAMOS UNA , Y EL NUMERO DE DECIMALES QUE QUEREMOS AGREGAR)
numero = round(12.345678,2)

print(numero)

